---
# Homelab-specific overrides
- name: Include homelab-specific variables
  include_vars: "homelab.yml"
- name: Update homelab-specific variables # noqa ignore-errors
  set_fact:
    mysql_users: "{{ mysql_users + mysql_homelab_users }}"
  # continue on if our users can't be added for sone reason (for example, if vault is unreachable)
  retries: 3
  delay: 5
  ignore_errors: true

# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages:
      "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL.
- include_tasks: configure.yml
- include_tasks: secure-installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: replication.yml
